pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }
    }
    archiveArtifacts 'C:\Users\Rusla\eclipse-workspace\beer\target\*.jar'
}